### PR TITLE
add option to render grid

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #6.

### CODE REVIEW

**Comment by AndyZe** [comment]
That algorithm makes sense and it looks more symmetric. The CPU load is also lower (~22% for my method, ~14% for yours).

You do get larger cell sizes around the edges and it's 28 more lines of code. Overall, I think it's a win.

**Comment by dirk-thomas** [comment]
The number of calls to `invertPixels` might actually contribute to the CPU usage. Would you mind trying to convert `invertPixels` into a macro and see if that lowers the CPU usage?

**Comment by AndyZe** [comment]
Here's a breakdown. It doesn't completely jive with what I had earlier ... maybe I was running another process that threw those off.

Mine w/ inline invertPixels(): 10-11% CPU load
Mine unmodified: 10-14%
Mine w/ macro: 10-17%  (I'm confused about why it was worse...)
Yours: 11-17%

**Comment by AndyZe** [comment]
Anyway, I'm going to be away from my computer for awhile. Whatever you choose is fine.

**Comment by dirk-thomas** [comment]
Interesting that the macro did make it worse. I updated the `invertPixel` function a little bit in a67881258dfb2d3a4d458efc127f2fa5e1c61c4b.

I will go ahead and merge this feature as-is. If there is a need we can still update it in the future. Thank you for providing the patch and working with me on getting it merged.

**Comment by AndyZe** [comment]
Why not make invertPixels() inline? The only downside I see is that I couldn't get it to compile as virtual.

**Comment by dirk-thomas** [comment]
Adding `inline` is only a hint to the compiler. It might already do it without the hint and it might not do it even though the method has the attribute. That would require more detailed debugging to confirm it actually makes a difference.

**Pull request merged**
