### PR TITLE
Make variable conversion_mat_ local to avoid race conditions

### PR DESCRIPTION
**Pull request by mvieth**
Fixes https://github.com/ros-visualization/rqt_image_view/issues/26

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Have you checked what this patch means in terms of allocating / deallocating the image matrix?

**Comment by mvieth** [comment]
I tried to analyze it with valgrind's massif, but I got not useful information regarding the image matrices.
However, I don't think it makes a difference: In [this line](https://github.com/ros-visualization/rqt_image_view/pull/27/files#diff-b3a8fa0c6df75e04a4fe8735f4bce8d5R560) there is nothing allocated AFAIK, and later in [this line](https://github.com/ros-visualization/rqt_image_view/pull/27/files#diff-b3a8fa0c6df75e04a4fe8735f4bce8d5R565) the data is shared, so there may be no additional allocs/deallocs. Overall, the other image processing functions are probably anyway more costly than an allocation/deallocation.
In terms of performance/CPU usage/memory usage, this patch was not better or worse than before.

**Comment by mvieth** [comment]
@dirk-thomas Anything else you want me to investigate?

**Comment by dirk-thomas** [comment]
I apologize that this wasn't looked at earlier. Unfortunately the `rqt` plugin repositories are not getting much attention.

The patch in this PR changes public API which makes it much harder to consider merging it. But after being able to reproduce the issue locally the patch helped me narrowing down what the actual problem was.

It is intentional that the same `cv::Mat` instance `conversion_mat_` is used repeatedly to avoid the extra allocation / deallocation. The critical part is that reusing it when the topic changes isn't feasible. Therefore it should be sufficient `release()` the matrix on topic change (which also won't require any public API changes).

Please see #40 for my proposed patch with which I was unable to reproduce the problem anymore. Assuming it will replace the changes from this PR I will go ahead and close this ticket.

**Pull request closed without merging**
