### PR TITLE
Use image_transport and cv_bridge targets

### LINKED ISSUE #61: rqt_image_view failing to build on ROS 2 build farm
ROS distro: Rolling
Version: 1.1.1-1
Platforms:
  * [Ubuntu AMD64](https://build.ros2.org/job/Rbin_uF64__rqt_image_view__ubuntu_focal_amd64__binary/)
  * [Ubuntu ARM64](https://build.ros2.org/job/Rbin_ufv8_uFv8__rqt_image_view__ubuntu_focal_arm64__binary/)
  * [RHEL AMD64](https://build.ros2.org/job/Rbin_rhel_el864__rqt_image_view__rhel_8_x86_64__binary/)

This package version was building previously it is probable that this build failure is the result of changes in dependencies.

```
[ 50%] Building CXX object CMakeFiles/rqt_image_view.dir/src/rqt_image_view/image_view.cpp.o
/usr/lib/ccache/c++  -DDEFAULT_RMW_IMPLEMENTATION=rmw_cyclonedds_cpp -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DRCUTILS_ENABLE_FAULT_INJECTION -Drqt_image_view_EXPORTS -I/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/obj-x86_64-linux-gnu -I/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1 -I/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/include -isystem /opt/ros/rolling/include -isystem /opt/ros/rolling/include/pluginlib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/opencv4 -isystem /opt/ros/rolling/include/class_loader  -g -O2 -fdebug-prefix-map=/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -Wall -Wextra -Wpedantic -fPIC -std=gnu++17 -o CMakeFiles/rqt_image_view.dir/src/rqt_image_view/image_view.cpp.o -c /tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/src/rqt_image_view/image_view.cpp
In file included from /tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/src/rqt_image_view/image_view.cpp:33:
/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/include/rqt_image_view/image_view.h:40:10: fatal error: image_transport/image_transport.hpp: No such file or directory
   40 | #include <image_transport/image_transport.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [CMakeFiles/rqt_image_view.dir/build.make:78: CMakeFiles/rqt_image_view.dir/src/rqt_image_view/image_view.cpp.o] Error 1
make[4]: Leaving directory '/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/obj-x86_64-linux-gnu'
make[3]: *** [CMakeFiles/Makefile2:81: CMakeFiles/rqt_image_view.dir/all] Error 2
make[3]: Leaving directory '/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/obj-x86_64-linux-gnu'
make[2]: *** [Makefile:144: all] Error 2
make[2]: Leaving directory '/tmp/binarydeb/ros-rolling-rqt-image-view-1.1.1/obj-x86_64-linux-gnu'
```

### PR DESCRIPTION
**Pull request by sloretz**
Fixes #61
~:warning: This needs to be targeted at a ROS Rolling specific branch.~ **Done**

### CODE REVIEW

**Comment by sloretz** [comment]
Rolling PR job failed because it used `ros-rolling-image-transport` 3.1.1, but the target is in 3.1.2. The PR has been merged: https://github.com/ros/rosdistro/pull/31776 , so maybe the rolling image hasn't been updated yet?

**Review by mabelzhang — APPROVED** [review]

**Comment by mabelzhang** [comment]
I approved but maybe the checks should be rerun?

**Comment by sloretz** [comment]
> I approved but maybe the checks should be rerun?

Yeah, I'm not totally sure how to test this. The rolling jobs don't seem to have built the latest versions of it's dependencies yet. I pushed another commit since I think it will have the same issue with cv_bridge when vision_opencv gets a release. I'll try a local build and report back.

**Comment by sloretz** [comment]
> I'll try a local build and report back.

With the latest version of [vision_opencv](https://github.com/ros-perception/vision_opencv/) and this PR this package builds successfully. I tested that I can load the plugin in rqt and visualize an image using `image_tools` `cam2image` as a test source. I think that's the best I can test this PR, and the results LGTM

**Review by mabelzhang — APPROVED** [review]
Thanks!!

**Comment by nuclearsandwich** [comment]
> The rolling jobs don't seem to have built the latest versions of it's dependencies yet. I pushed another commit since I think it will have the same issue with cv_bridge when vision_opencv gets a release. I'll try a local build and report back.

This is a tradeoff we pay since PR jobs run based on the `testing` repository but the failure of rqt_image_view is blocking the sync to testing from building since ros-desktop can't be built without this package. :upside_down_face:

**Pull request merged**
