### PR TITLE
Added missing: #include <QSet>

### PR DESCRIPTION
**Pull request by greghab**
failed to compile. 
See: https://github.com/ros-melodic-arch/ros-melodic-rqt-image-view/issues/1
And #29 : https://github.com/ros-visualization/rqt_image_view/issues/29

### CODE REVIEW

**Comment by cubimon** [comment]
Please notice me senpai @dirk-thomas

**Comment by jwhendy** [comment]
This resolved for me.

**Comment by dirk-thomas** [comment]
I don't think this patch is sufficient as is. The header `image_view.h` also uses `QSet` and is being included by the `.cpp` file. If the `.cpp` fails to compile downstream packages should fail when trying to use the header file. Therefore I think the missing include should be moved to the header instead.

**Comment by cubimon** [comment]
@greghab can you move the include statement to the header? It makes more sense

**Comment by dirk-thomas** [comment]
Replaced by #31.

**Pull request closed without merging**
